namespace iCantina.Views
{
    partial class EstudanteForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EstudanteForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dataGridViewCliente = new System.Windows.Forms.DataGridView();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btneEdite = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnInserir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbNome = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbNIF = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbNumeroEstudante = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbSaldo = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewCliente)).BeginInit();
            this.SuspendLayout();
            // 
            // txtSearch
            // 
            this.txtSearch.AcceptsReturn = false;
            this.txtSearch.AcceptsTab = false;
            this.txtSearch.AnimationSpeed = 200;
            this.txtSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearch.BackColor = System.Drawing.Color.Transparent;
            this.txtSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearch.BackgroundImage")));
            this.txtSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSearch.BorderRadius = 25;
            this.txtSearch.BorderThickness = 1;
            this.txtSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSearch.DefaultText = "";
            this.txtSearch.FillColor = System.Drawing.Color.White;
            this.txtSearch.HideSelection = true;
            this.txtSearch.IconLeft = null;
            this.txtSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.IconPadding = 10;
            this.txtSearch.IconRight = null;
            this.txtSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.Lines = new string[0];
            this.txtSearch.Location = new System.Drawing.Point(311, 76);
            this.txtSearch.MaxLength = 32767;
            this.txtSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearch.Modified = false;
            this.txtSearch.Multiline = false;
            this.txtSearch.Name = "txtSearch";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearch.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnIdleState = stateProperties44;
            this.txtSearch.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearch.PasswordChar = '\0';
            this.txtSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearch.PlaceholderText = "Pesquisar estudante";
            this.txtSearch.ReadOnly = false;
            this.txtSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearch.SelectedText = "";
            this.txtSearch.SelectionLength = 0;
            this.txtSearch.SelectionStart = 0;
            this.txtSearch.ShortcutsEnabled = true;
            this.txtSearch.Size = new System.Drawing.Size(462, 37);
            this.txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearch.TabIndex = 24;
            this.txtSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearch.TextMarginBottom = 0;
            this.txtSearch.TextMarginLeft = 3;
            this.txtSearch.TextMarginTop = 0;
            this.txtSearch.TextPlaceholder = "Pesquisar estudante";
            this.txtSearch.UseSystemPasswordChar = false;
            this.txtSearch.WordWrap = true;
            this.txtSearch.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtSearch_KeyPress);
            // 
            // dataGridViewCliente
            // 
            this.dataGridViewCliente.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridViewCliente.Location = new System.Drawing.Point(311, 119);
            this.dataGridViewCliente.Name = "dataGridViewCliente";
            this.dataGridViewCliente.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.AutoSizeToAllHeaders;
            this.dataGridViewCliente.Size = new System.Drawing.Size(462, 347);
            this.dataGridViewCliente.TabIndex = 23;
            this.dataGridViewCliente.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridViewCliente_CellClick);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Eliminar";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges7;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.IdleBorderRadius = 25;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(22, 427);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 25;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 25;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.BorderRadius = 25;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 25;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(239, 39);
            this.bunifuButton3.TabIndex = 22;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // btneEdite
            // 
            this.btneEdite.AllowAnimations = true;
            this.btneEdite.AllowMouseEffects = true;
            this.btneEdite.AllowToggling = false;
            this.btneEdite.AnimationSpeed = 200;
            this.btneEdite.AutoGenerateColors = false;
            this.btneEdite.AutoRoundBorders = false;
            this.btneEdite.AutoSizeLeftIcon = true;
            this.btneEdite.AutoSizeRightIcon = true;
            this.btneEdite.BackColor = System.Drawing.Color.Transparent;
            this.btneEdite.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btneEdite.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btneEdite.BackgroundImage")));
            this.btneEdite.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.ButtonText = "Editar";
            this.btneEdite.ButtonTextMarginLeft = 0;
            this.btneEdite.ColorContrastOnClick = 45;
            this.btneEdite.ColorContrastOnHover = 45;
            this.btneEdite.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btneEdite.CustomizableEdges = borderEdges8;
            this.btneEdite.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btneEdite.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneEdite.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btneEdite.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btneEdite.Enabled = false;
            this.btneEdite.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btneEdite.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btneEdite.ForeColor = System.Drawing.Color.White;
            this.btneEdite.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btneEdite.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btneEdite.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btneEdite.IconMarginLeft = 11;
            this.btneEdite.IconPadding = 10;
            this.btneEdite.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btneEdite.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btneEdite.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btneEdite.IconSize = 25;
            this.btneEdite.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.IdleBorderRadius = 25;
            this.btneEdite.IdleBorderThickness = 1;
            this.btneEdite.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.IdleIconLeftImage = null;
            this.btneEdite.IdleIconRightImage = null;
            this.btneEdite.IndicateFocus = false;
            this.btneEdite.Location = new System.Drawing.Point(167, 382);
            this.btneEdite.Name = "btneEdite";
            this.btneEdite.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneEdite.OnDisabledState.BorderRadius = 25;
            this.btneEdite.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.OnDisabledState.BorderThickness = 1;
            this.btneEdite.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btneEdite.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btneEdite.OnDisabledState.IconLeftImage = null;
            this.btneEdite.OnDisabledState.IconRightImage = null;
            this.btneEdite.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btneEdite.onHoverState.BorderRadius = 25;
            this.btneEdite.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.onHoverState.BorderThickness = 1;
            this.btneEdite.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btneEdite.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btneEdite.onHoverState.IconLeftImage = null;
            this.btneEdite.onHoverState.IconRightImage = null;
            this.btneEdite.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.OnIdleState.BorderRadius = 25;
            this.btneEdite.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.OnIdleState.BorderThickness = 1;
            this.btneEdite.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btneEdite.OnIdleState.IconLeftImage = null;
            this.btneEdite.OnIdleState.IconRightImage = null;
            this.btneEdite.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btneEdite.OnPressedState.BorderRadius = 25;
            this.btneEdite.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.OnPressedState.BorderThickness = 1;
            this.btneEdite.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btneEdite.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btneEdite.OnPressedState.IconLeftImage = null;
            this.btneEdite.OnPressedState.IconRightImage = null;
            this.btneEdite.Size = new System.Drawing.Size(94, 39);
            this.btneEdite.TabIndex = 21;
            this.btneEdite.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btneEdite.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btneEdite.TextMarginLeft = 0;
            this.btneEdite.TextPadding = new System.Windows.Forms.Padding(0);
            this.btneEdite.UseDefaultRadiusAndThickness = true;
            this.btneEdite.Click += new System.EventHandler(this.btneEdite_Click);
            // 
            // btnInserir
            // 
            this.btnInserir.AllowAnimations = true;
            this.btnInserir.AllowMouseEffects = true;
            this.btnInserir.AllowToggling = false;
            this.btnInserir.AnimationSpeed = 200;
            this.btnInserir.AutoGenerateColors = false;
            this.btnInserir.AutoRoundBorders = false;
            this.btnInserir.AutoSizeLeftIcon = true;
            this.btnInserir.AutoSizeRightIcon = true;
            this.btnInserir.BackColor = System.Drawing.Color.Transparent;
            this.btnInserir.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnInserir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInserir.BackgroundImage")));
            this.btnInserir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.ButtonText = "Inserir";
            this.btnInserir.ButtonTextMarginLeft = 0;
            this.btnInserir.ColorContrastOnClick = 45;
            this.btnInserir.ColorContrastOnHover = 45;
            this.btnInserir.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnInserir.CustomizableEdges = borderEdges9;
            this.btnInserir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInserir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInserir.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInserir.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInserir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInserir.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnInserir.ForeColor = System.Drawing.Color.White;
            this.btnInserir.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInserir.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInserir.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInserir.IconMarginLeft = 11;
            this.btnInserir.IconPadding = 10;
            this.btnInserir.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInserir.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInserir.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInserir.IconSize = 25;
            this.btnInserir.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.IdleBorderRadius = 25;
            this.btnInserir.IdleBorderThickness = 1;
            this.btnInserir.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.IdleIconLeftImage = null;
            this.btnInserir.IdleIconRightImage = null;
            this.btnInserir.IndicateFocus = false;
            this.btnInserir.Location = new System.Drawing.Point(22, 380);
            this.btnInserir.Name = "btnInserir";
            this.btnInserir.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInserir.OnDisabledState.BorderRadius = 25;
            this.btnInserir.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.OnDisabledState.BorderThickness = 1;
            this.btnInserir.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInserir.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInserir.OnDisabledState.IconLeftImage = null;
            this.btnInserir.OnDisabledState.IconRightImage = null;
            this.btnInserir.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnInserir.onHoverState.BorderRadius = 25;
            this.btnInserir.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.onHoverState.BorderThickness = 1;
            this.btnInserir.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnInserir.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInserir.onHoverState.IconLeftImage = null;
            this.btnInserir.onHoverState.IconRightImage = null;
            this.btnInserir.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.OnIdleState.BorderRadius = 25;
            this.btnInserir.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.OnIdleState.BorderThickness = 1;
            this.btnInserir.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnInserir.OnIdleState.IconLeftImage = null;
            this.btnInserir.OnIdleState.IconRightImage = null;
            this.btnInserir.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInserir.OnPressedState.BorderRadius = 25;
            this.btnInserir.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.OnPressedState.BorderThickness = 1;
            this.btnInserir.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInserir.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInserir.OnPressedState.IconLeftImage = null;
            this.btnInserir.OnPressedState.IconRightImage = null;
            this.btnInserir.Size = new System.Drawing.Size(129, 39);
            this.btnInserir.TabIndex = 20;
            this.btnInserir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInserir.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInserir.TextMarginLeft = 0;
            this.btnInserir.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInserir.UseDefaultRadiusAndThickness = true;
            this.btnInserir.Click += new System.EventHandler(this.btnInserir_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel2.Location = new System.Drawing.Point(22, 76);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(51, 25);
            this.bunifuLabel2.TabIndex = 15;
            this.bunifuLabel2.Text = "Nome";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbNome
            // 
            this.tbNome.AcceptsReturn = false;
            this.tbNome.AcceptsTab = false;
            this.tbNome.AnimationSpeed = 200;
            this.tbNome.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbNome.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbNome.BackColor = System.Drawing.Color.Transparent;
            this.tbNome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbNome.BackgroundImage")));
            this.tbNome.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbNome.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbNome.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbNome.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbNome.BorderRadius = 25;
            this.tbNome.BorderThickness = 1;
            this.tbNome.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbNome.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNome.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbNome.DefaultText = "";
            this.tbNome.FillColor = System.Drawing.Color.White;
            this.tbNome.HideSelection = true;
            this.tbNome.IconLeft = null;
            this.tbNome.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNome.IconPadding = 10;
            this.tbNome.IconRight = null;
            this.tbNome.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNome.Lines = new string[0];
            this.tbNome.Location = new System.Drawing.Point(22, 115);
            this.tbNome.MaxLength = 22222;
            this.tbNome.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbNome.Modified = false;
            this.tbNome.Multiline = false;
            this.tbNome.Name = "tbNome";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNome.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbNome.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNome.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNome.OnIdleState = stateProperties48;
            this.tbNome.Padding = new System.Windows.Forms.Padding(3);
            this.tbNome.PasswordChar = '\0';
            this.tbNome.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbNome.PlaceholderText = "";
            this.tbNome.ReadOnly = false;
            this.tbNome.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbNome.SelectedText = "";
            this.tbNome.SelectionLength = 0;
            this.tbNome.SelectionStart = 0;
            this.tbNome.ShortcutsEnabled = true;
            this.tbNome.Size = new System.Drawing.Size(239, 37);
            this.tbNome.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbNome.TabIndex = 14;
            this.tbNome.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbNome.TextMarginBottom = 0;
            this.tbNome.TextMarginLeft = 3;
            this.tbNome.TextMarginTop = 0;
            this.tbNome.TextPlaceholder = "";
            this.tbNome.UseSystemPasswordChar = false;
            this.tbNome.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(22, 24);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(235, 32);
            this.bunifuLabel1.TabIndex = 13;
            this.bunifuLabel1.Text = "Gestão de Estudantes";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel3.Location = new System.Drawing.Point(22, 154);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(28, 25);
            this.bunifuLabel3.TabIndex = 26;
            this.bunifuLabel3.Text = "NIF";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbNIF
            // 
            this.tbNIF.AcceptsReturn = false;
            this.tbNIF.AcceptsTab = false;
            this.tbNIF.AnimationSpeed = 200;
            this.tbNIF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbNIF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbNIF.BackColor = System.Drawing.Color.Transparent;
            this.tbNIF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbNIF.BackgroundImage")));
            this.tbNIF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbNIF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbNIF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbNIF.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbNIF.BorderRadius = 25;
            this.tbNIF.BorderThickness = 1;
            this.tbNIF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbNIF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNIF.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbNIF.DefaultText = "";
            this.tbNIF.FillColor = System.Drawing.Color.White;
            this.tbNIF.HideSelection = true;
            this.tbNIF.IconLeft = null;
            this.tbNIF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNIF.IconPadding = 10;
            this.tbNIF.IconRight = null;
            this.tbNIF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNIF.Lines = new string[0];
            this.tbNIF.Location = new System.Drawing.Point(22, 186);
            this.tbNIF.MaxLength = 9;
            this.tbNIF.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbNIF.Modified = false;
            this.tbNIF.Multiline = false;
            this.tbNIF.Name = "tbNIF";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNIF.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbNIF.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNIF.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNIF.OnIdleState = stateProperties52;
            this.tbNIF.Padding = new System.Windows.Forms.Padding(3);
            this.tbNIF.PasswordChar = '\0';
            this.tbNIF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbNIF.PlaceholderText = "";
            this.tbNIF.ReadOnly = false;
            this.tbNIF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbNIF.SelectedText = "";
            this.tbNIF.SelectionLength = 0;
            this.tbNIF.SelectionStart = 0;
            this.tbNIF.ShortcutsEnabled = true;
            this.tbNIF.Size = new System.Drawing.Size(239, 37);
            this.tbNIF.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbNIF.TabIndex = 25;
            this.tbNIF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbNIF.TextMarginBottom = 0;
            this.tbNIF.TextMarginLeft = 3;
            this.tbNIF.TextMarginTop = 0;
            this.tbNIF.TextPlaceholder = "";
            this.tbNIF.UseSystemPasswordChar = false;
            this.tbNIF.WordWrap = true;
            this.tbNIF.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.validarNumero);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel4.Location = new System.Drawing.Point(22, 229);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(183, 25);
            this.bunifuLabel4.TabIndex = 28;
            this.bunifuLabel4.Text = "Número de estudante";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbNumeroEstudante
            // 
            this.tbNumeroEstudante.AcceptsReturn = false;
            this.tbNumeroEstudante.AcceptsTab = false;
            this.tbNumeroEstudante.AnimationSpeed = 200;
            this.tbNumeroEstudante.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbNumeroEstudante.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbNumeroEstudante.BackColor = System.Drawing.Color.Transparent;
            this.tbNumeroEstudante.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbNumeroEstudante.BackgroundImage")));
            this.tbNumeroEstudante.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbNumeroEstudante.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbNumeroEstudante.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbNumeroEstudante.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbNumeroEstudante.BorderRadius = 25;
            this.tbNumeroEstudante.BorderThickness = 1;
            this.tbNumeroEstudante.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbNumeroEstudante.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNumeroEstudante.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbNumeroEstudante.DefaultText = "";
            this.tbNumeroEstudante.FillColor = System.Drawing.Color.White;
            this.tbNumeroEstudante.HideSelection = true;
            this.tbNumeroEstudante.IconLeft = null;
            this.tbNumeroEstudante.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNumeroEstudante.IconPadding = 10;
            this.tbNumeroEstudante.IconRight = null;
            this.tbNumeroEstudante.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNumeroEstudante.Lines = new string[0];
            this.tbNumeroEstudante.Location = new System.Drawing.Point(18, 260);
            this.tbNumeroEstudante.MaxLength = 7;
            this.tbNumeroEstudante.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbNumeroEstudante.Modified = false;
            this.tbNumeroEstudante.Multiline = false;
            this.tbNumeroEstudante.Name = "tbNumeroEstudante";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNumeroEstudante.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbNumeroEstudante.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNumeroEstudante.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNumeroEstudante.OnIdleState = stateProperties56;
            this.tbNumeroEstudante.Padding = new System.Windows.Forms.Padding(3);
            this.tbNumeroEstudante.PasswordChar = '\0';
            this.tbNumeroEstudante.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbNumeroEstudante.PlaceholderText = "";
            this.tbNumeroEstudante.ReadOnly = false;
            this.tbNumeroEstudante.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbNumeroEstudante.SelectedText = "";
            this.tbNumeroEstudante.SelectionLength = 0;
            this.tbNumeroEstudante.SelectionStart = 0;
            this.tbNumeroEstudante.ShortcutsEnabled = true;
            this.tbNumeroEstudante.Size = new System.Drawing.Size(239, 37);
            this.tbNumeroEstudante.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbNumeroEstudante.TabIndex = 27;
            this.tbNumeroEstudante.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbNumeroEstudante.TextMarginBottom = 0;
            this.tbNumeroEstudante.TextMarginLeft = 3;
            this.tbNumeroEstudante.TextMarginTop = 0;
            this.tbNumeroEstudante.TextPlaceholder = "";
            this.tbNumeroEstudante.UseSystemPasswordChar = false;
            this.tbNumeroEstudante.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel5.Location = new System.Drawing.Point(26, 297);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(47, 25);
            this.bunifuLabel5.TabIndex = 30;
            this.bunifuLabel5.Text = "Saldo";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbSaldo
            // 
            this.tbSaldo.AcceptsReturn = false;
            this.tbSaldo.AcceptsTab = false;
            this.tbSaldo.AnimationSpeed = 200;
            this.tbSaldo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSaldo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSaldo.BackColor = System.Drawing.Color.Transparent;
            this.tbSaldo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSaldo.BackgroundImage")));
            this.tbSaldo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSaldo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSaldo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSaldo.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSaldo.BorderRadius = 25;
            this.tbSaldo.BorderThickness = 1;
            this.tbSaldo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSaldo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSaldo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbSaldo.DefaultText = "";
            this.tbSaldo.FillColor = System.Drawing.Color.White;
            this.tbSaldo.HideSelection = true;
            this.tbSaldo.IconLeft = null;
            this.tbSaldo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSaldo.IconPadding = 10;
            this.tbSaldo.IconRight = null;
            this.tbSaldo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSaldo.Lines = new string[0];
            this.tbSaldo.Location = new System.Drawing.Point(22, 328);
            this.tbSaldo.MaxLength = 7;
            this.tbSaldo.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSaldo.Modified = false;
            this.tbSaldo.Multiline = false;
            this.tbSaldo.Name = "tbSaldo";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSaldo.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSaldo.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSaldo.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSaldo.OnIdleState = stateProperties60;
            this.tbSaldo.Padding = new System.Windows.Forms.Padding(3);
            this.tbSaldo.PasswordChar = '\0';
            this.tbSaldo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSaldo.PlaceholderText = "";
            this.tbSaldo.ReadOnly = false;
            this.tbSaldo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSaldo.SelectedText = "";
            this.tbSaldo.SelectionLength = 0;
            this.tbSaldo.SelectionStart = 0;
            this.tbSaldo.ShortcutsEnabled = true;
            this.tbSaldo.Size = new System.Drawing.Size(239, 37);
            this.tbSaldo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSaldo.TabIndex = 29;
            this.tbSaldo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSaldo.TextMarginBottom = 0;
            this.tbSaldo.TextMarginLeft = 3;
            this.tbSaldo.TextMarginTop = 0;
            this.tbSaldo.TextPlaceholder = "";
            this.tbSaldo.UseSystemPasswordChar = false;
            this.tbSaldo.WordWrap = true;
            this.tbSaldo.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.validarNumero);
            // 
            // EstudanteForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.ClientSize = new System.Drawing.Size(799, 489);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.tbSaldo);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.tbNumeroEstudante);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.tbNIF);
            this.Controls.Add(this.txtSearch);
            this.Controls.Add(this.dataGridViewCliente);
            this.Controls.Add(this.bunifuButton3);
            this.Controls.Add(this.btneEdite);
            this.Controls.Add(this.btnInserir);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.tbNome);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "EstudanteForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "ClienteForm";
            this.Load += new System.EventHandler(this.EstudanteForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewCliente)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
        private System.Windows.Forms.DataGridView dataGridViewCliente;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btneEdite;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInserir;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox tbNome;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox tbNIF;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox tbNumeroEstudante;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox tbSaldo;
    }
}