namespace iCantina
{
    partial class FuncionarioForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FuncionarioForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbNome = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbNIF = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnInserir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btneEdite = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridViewfFuncionario = new System.Windows.Forms.DataGridView();
            this.txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewfFuncionario)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(254, 32);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Gestão de Funcionários";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbNome
            // 
            this.tbNome.AcceptsReturn = false;
            this.tbNome.AcceptsTab = false;
            this.tbNome.AnimationSpeed = 200;
            this.tbNome.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbNome.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbNome.BackColor = System.Drawing.Color.Transparent;
            this.tbNome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbNome.BackgroundImage")));
            this.tbNome.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbNome.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbNome.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbNome.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbNome.BorderRadius = 25;
            this.tbNome.BorderThickness = 1;
            this.tbNome.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbNome.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNome.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbNome.DefaultText = "";
            this.tbNome.FillColor = System.Drawing.Color.White;
            this.tbNome.HideSelection = true;
            this.tbNome.IconLeft = null;
            this.tbNome.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNome.IconPadding = 10;
            this.tbNome.IconRight = null;
            this.tbNome.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNome.Lines = new string[0];
            this.tbNome.Location = new System.Drawing.Point(21, 81);
            this.tbNome.MaxLength = 32767;
            this.tbNome.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbNome.Modified = false;
            this.tbNome.Multiline = false;
            this.tbNome.Name = "tbNome";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNome.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbNome.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNome.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNome.OnIdleState = stateProperties4;
            this.tbNome.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbNome.PasswordChar = '\0';
            this.tbNome.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbNome.PlaceholderText = "Introduza o nome";
            this.tbNome.ReadOnly = false;
            this.tbNome.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbNome.SelectedText = "";
            this.tbNome.SelectionLength = 0;
            this.tbNome.SelectionStart = 0;
            this.tbNome.ShortcutsEnabled = true;
            this.tbNome.Size = new System.Drawing.Size(260, 37);
            this.tbNome.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbNome.TabIndex = 1;
            this.tbNome.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbNome.TextMarginBottom = 0;
            this.tbNome.TextMarginLeft = 3;
            this.tbNome.TextMarginTop = 0;
            this.tbNome.TextPlaceholder = "Introduza o nome";
            this.tbNome.UseSystemPasswordChar = false;
            this.tbNome.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel2.Location = new System.Drawing.Point(21, 50);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(51, 25);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Nome";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbNIF
            // 
            this.tbNIF.AcceptsReturn = false;
            this.tbNIF.AcceptsTab = false;
            this.tbNIF.AnimationSpeed = 200;
            this.tbNIF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbNIF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbNIF.BackColor = System.Drawing.Color.Transparent;
            this.tbNIF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbNIF.BackgroundImage")));
            this.tbNIF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbNIF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbNIF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbNIF.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbNIF.BorderRadius = 25;
            this.tbNIF.BorderThickness = 1;
            this.tbNIF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbNIF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNIF.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbNIF.DefaultText = "";
            this.tbNIF.FillColor = System.Drawing.Color.White;
            this.tbNIF.HideSelection = true;
            this.tbNIF.IconLeft = null;
            this.tbNIF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNIF.IconPadding = 10;
            this.tbNIF.IconRight = null;
            this.tbNIF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNIF.Lines = new string[0];
            this.tbNIF.Location = new System.Drawing.Point(21, 163);
            this.tbNIF.MaxLength = 9;
            this.tbNIF.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbNIF.Modified = false;
            this.tbNIF.Multiline = false;
            this.tbNIF.Name = "tbNIF";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNIF.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbNIF.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNIF.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNIF.OnIdleState = stateProperties8;
            this.tbNIF.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbNIF.PasswordChar = '\0';
            this.tbNIF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbNIF.PlaceholderText = "";
            this.tbNIF.ReadOnly = false;
            this.tbNIF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbNIF.SelectedText = "";
            this.tbNIF.SelectionLength = 0;
            this.tbNIF.SelectionStart = 0;
            this.tbNIF.ShortcutsEnabled = true;
            this.tbNIF.Size = new System.Drawing.Size(260, 37);
            this.tbNIF.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbNIF.TabIndex = 4;
            this.tbNIF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbNIF.TextMarginBottom = 0;
            this.tbNIF.TextMarginLeft = 3;
            this.tbNIF.TextMarginTop = 0;
            this.tbNIF.TextPlaceholder = "";
            this.tbNIF.UseSystemPasswordChar = false;
            this.tbNIF.WordWrap = true;
            this.tbNIF.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.tbNIF_KeyPress);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel4.Location = new System.Drawing.Point(21, 206);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(85, 25);
            this.bunifuLabel4.TabIndex = 5;
            this.bunifuLabel4.Text = "Username";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel4.Click += new System.EventHandler(this.bunifuLabel4_Click);
            // 
            // tbUsername
            // 
            this.tbUsername.AcceptsReturn = false;
            this.tbUsername.AcceptsTab = false;
            this.tbUsername.AnimationSpeed = 200;
            this.tbUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbUsername.BackColor = System.Drawing.Color.Transparent;
            this.tbUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbUsername.BackgroundImage")));
            this.tbUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbUsername.BorderRadius = 25;
            this.tbUsername.BorderThickness = 1;
            this.tbUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbUsername.DefaultText = "";
            this.tbUsername.FillColor = System.Drawing.Color.White;
            this.tbUsername.HideSelection = true;
            this.tbUsername.IconLeft = null;
            this.tbUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.IconPadding = 10;
            this.tbUsername.IconRight = null;
            this.tbUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbUsername.Lines = new string[0];
            this.tbUsername.Location = new System.Drawing.Point(12, 237);
            this.tbUsername.MaxLength = 32767;
            this.tbUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbUsername.Modified = false;
            this.tbUsername.Multiline = false;
            this.tbUsername.Name = "tbUsername";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbUsername.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbUsername.OnIdleState = stateProperties12;
            this.tbUsername.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tbUsername.PasswordChar = '\0';
            this.tbUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbUsername.PlaceholderText = "Introduza o Username";
            this.tbUsername.ReadOnly = false;
            this.tbUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbUsername.SelectedText = "";
            this.tbUsername.SelectionLength = 0;
            this.tbUsername.SelectionStart = 0;
            this.tbUsername.ShortcutsEnabled = true;
            this.tbUsername.Size = new System.Drawing.Size(260, 37);
            this.tbUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbUsername.TabIndex = 6;
            this.tbUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbUsername.TextMarginBottom = 0;
            this.tbUsername.TextMarginLeft = 3;
            this.tbUsername.TextMarginTop = 0;
            this.tbUsername.TextPlaceholder = "Introduza o Username";
            this.tbUsername.UseSystemPasswordChar = false;
            this.tbUsername.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel3.Location = new System.Drawing.Point(21, 132);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(28, 25);
            this.bunifuLabel3.TabIndex = 7;
            this.bunifuLabel3.Text = "NIF";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnInserir
            // 
            this.btnInserir.AllowAnimations = true;
            this.btnInserir.AllowMouseEffects = true;
            this.btnInserir.AllowToggling = false;
            this.btnInserir.AnimationSpeed = 200;
            this.btnInserir.AutoGenerateColors = false;
            this.btnInserir.AutoRoundBorders = false;
            this.btnInserir.AutoSizeLeftIcon = true;
            this.btnInserir.AutoSizeRightIcon = true;
            this.btnInserir.BackColor = System.Drawing.Color.Transparent;
            this.btnInserir.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnInserir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInserir.BackgroundImage")));
            this.btnInserir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.ButtonText = "Inserir";
            this.btnInserir.ButtonTextMarginLeft = 0;
            this.btnInserir.ColorContrastOnClick = 45;
            this.btnInserir.ColorContrastOnHover = 45;
            this.btnInserir.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnInserir.CustomizableEdges = borderEdges1;
            this.btnInserir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInserir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInserir.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInserir.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInserir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInserir.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnInserir.ForeColor = System.Drawing.Color.White;
            this.btnInserir.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInserir.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInserir.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInserir.IconMarginLeft = 11;
            this.btnInserir.IconPadding = 10;
            this.btnInserir.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInserir.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInserir.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInserir.IconSize = 25;
            this.btnInserir.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.IdleBorderRadius = 25;
            this.btnInserir.IdleBorderThickness = 1;
            this.btnInserir.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.IdleIconLeftImage = null;
            this.btnInserir.IdleIconRightImage = null;
            this.btnInserir.IndicateFocus = false;
            this.btnInserir.Location = new System.Drawing.Point(21, 299);
            this.btnInserir.Name = "btnInserir";
            this.btnInserir.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInserir.OnDisabledState.BorderRadius = 25;
            this.btnInserir.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.OnDisabledState.BorderThickness = 1;
            this.btnInserir.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInserir.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInserir.OnDisabledState.IconLeftImage = null;
            this.btnInserir.OnDisabledState.IconRightImage = null;
            this.btnInserir.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnInserir.onHoverState.BorderRadius = 25;
            this.btnInserir.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.onHoverState.BorderThickness = 1;
            this.btnInserir.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnInserir.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInserir.onHoverState.IconLeftImage = null;
            this.btnInserir.onHoverState.IconRightImage = null;
            this.btnInserir.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.OnIdleState.BorderRadius = 25;
            this.btnInserir.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.OnIdleState.BorderThickness = 1;
            this.btnInserir.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnInserir.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnInserir.OnIdleState.IconLeftImage = null;
            this.btnInserir.OnIdleState.IconRightImage = null;
            this.btnInserir.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInserir.OnPressedState.BorderRadius = 25;
            this.btnInserir.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInserir.OnPressedState.BorderThickness = 1;
            this.btnInserir.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInserir.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInserir.OnPressedState.IconLeftImage = null;
            this.btnInserir.OnPressedState.IconRightImage = null;
            this.btnInserir.Size = new System.Drawing.Size(150, 39);
            this.btnInserir.TabIndex = 8;
            this.btnInserir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInserir.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInserir.TextMarginLeft = 0;
            this.btnInserir.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInserir.UseDefaultRadiusAndThickness = true;
            this.btnInserir.Click += new System.EventHandler(this.btnInserir_Click);
            // 
            // btneEdite
            // 
            this.btneEdite.AllowAnimations = true;
            this.btneEdite.AllowMouseEffects = true;
            this.btneEdite.AllowToggling = false;
            this.btneEdite.AnimationSpeed = 200;
            this.btneEdite.AutoGenerateColors = false;
            this.btneEdite.AutoRoundBorders = false;
            this.btneEdite.AutoSizeLeftIcon = true;
            this.btneEdite.AutoSizeRightIcon = true;
            this.btneEdite.BackColor = System.Drawing.Color.Transparent;
            this.btneEdite.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btneEdite.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btneEdite.BackgroundImage")));
            this.btneEdite.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.ButtonText = "Editar";
            this.btneEdite.ButtonTextMarginLeft = 0;
            this.btneEdite.ColorContrastOnClick = 45;
            this.btneEdite.ColorContrastOnHover = 45;
            this.btneEdite.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btneEdite.CustomizableEdges = borderEdges2;
            this.btneEdite.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btneEdite.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneEdite.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btneEdite.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btneEdite.Enabled = false;
            this.btneEdite.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btneEdite.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btneEdite.ForeColor = System.Drawing.Color.White;
            this.btneEdite.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btneEdite.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btneEdite.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btneEdite.IconMarginLeft = 11;
            this.btneEdite.IconPadding = 10;
            this.btneEdite.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btneEdite.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btneEdite.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btneEdite.IconSize = 25;
            this.btneEdite.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.IdleBorderRadius = 25;
            this.btneEdite.IdleBorderThickness = 1;
            this.btneEdite.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.IdleIconLeftImage = null;
            this.btneEdite.IdleIconRightImage = null;
            this.btneEdite.IndicateFocus = false;
            this.btneEdite.Location = new System.Drawing.Point(21, 344);
            this.btneEdite.Name = "btneEdite";
            this.btneEdite.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneEdite.OnDisabledState.BorderRadius = 25;
            this.btneEdite.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.OnDisabledState.BorderThickness = 1;
            this.btneEdite.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btneEdite.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btneEdite.OnDisabledState.IconLeftImage = null;
            this.btneEdite.OnDisabledState.IconRightImage = null;
            this.btneEdite.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btneEdite.onHoverState.BorderRadius = 25;
            this.btneEdite.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.onHoverState.BorderThickness = 1;
            this.btneEdite.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btneEdite.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btneEdite.onHoverState.IconLeftImage = null;
            this.btneEdite.onHoverState.IconRightImage = null;
            this.btneEdite.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.OnIdleState.BorderRadius = 25;
            this.btneEdite.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.OnIdleState.BorderThickness = 1;
            this.btneEdite.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btneEdite.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btneEdite.OnIdleState.IconLeftImage = null;
            this.btneEdite.OnIdleState.IconRightImage = null;
            this.btneEdite.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btneEdite.OnPressedState.BorderRadius = 25;
            this.btneEdite.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneEdite.OnPressedState.BorderThickness = 1;
            this.btneEdite.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btneEdite.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btneEdite.OnPressedState.IconLeftImage = null;
            this.btneEdite.OnPressedState.IconRightImage = null;
            this.btneEdite.Size = new System.Drawing.Size(150, 39);
            this.btneEdite.TabIndex = 9;
            this.btneEdite.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btneEdite.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btneEdite.TextMarginLeft = 0;
            this.btneEdite.TextPadding = new System.Windows.Forms.Padding(0);
            this.btneEdite.UseDefaultRadiusAndThickness = true;
            this.btneEdite.Click += new System.EventHandler(this.btneEdite_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Eliminar";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges3;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.IdleBorderRadius = 25;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(21, 389);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 25;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 25;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.BorderRadius = 25;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 25;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton3.TabIndex = 10;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // dataGridViewfFuncionario
            // 
            this.dataGridViewfFuncionario.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridViewfFuncionario.Location = new System.Drawing.Point(310, 110);
            this.dataGridViewfFuncionario.Name = "dataGridViewfFuncionario";
            this.dataGridViewfFuncionario.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.AutoSizeToAllHeaders;
            this.dataGridViewfFuncionario.Size = new System.Drawing.Size(442, 318);
            this.dataGridViewfFuncionario.TabIndex = 11;
            this.dataGridViewfFuncionario.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridViewfFuncionario_CellClick);
            // 
            // txtSearch
            // 
            this.txtSearch.AcceptsReturn = false;
            this.txtSearch.AcceptsTab = false;
            this.txtSearch.AnimationSpeed = 200;
            this.txtSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearch.BackColor = System.Drawing.Color.Transparent;
            this.txtSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearch.BackgroundImage")));
            this.txtSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSearch.BorderRadius = 25;
            this.txtSearch.BorderThickness = 1;
            this.txtSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSearch.DefaultText = "";
            this.txtSearch.FillColor = System.Drawing.Color.White;
            this.txtSearch.HideSelection = true;
            this.txtSearch.IconLeft = null;
            this.txtSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.IconPadding = 10;
            this.txtSearch.IconRight = null;
            this.txtSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.Lines = new string[0];
            this.txtSearch.Location = new System.Drawing.Point(310, 66);
            this.txtSearch.MaxLength = 32767;
            this.txtSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearch.Modified = false;
            this.txtSearch.Multiline = false;
            this.txtSearch.Name = "txtSearch";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearch.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnIdleState = stateProperties16;
            this.txtSearch.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtSearch.PasswordChar = '\0';
            this.txtSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearch.PlaceholderText = "Pesquisar funcionário";
            this.txtSearch.ReadOnly = false;
            this.txtSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearch.SelectedText = "";
            this.txtSearch.SelectionLength = 0;
            this.txtSearch.SelectionStart = 0;
            this.txtSearch.ShortcutsEnabled = true;
            this.txtSearch.Size = new System.Drawing.Size(442, 37);
            this.txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearch.TabIndex = 12;
            this.txtSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearch.TextMarginBottom = 0;
            this.txtSearch.TextMarginLeft = 3;
            this.txtSearch.TextMarginTop = 0;
            this.txtSearch.TextPlaceholder = "Pesquisar funcionário";
            this.txtSearch.UseSystemPasswordChar = false;
            this.txtSearch.WordWrap = true;
            this.txtSearch.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtSearch_KeyPress);
            // 
            // FuncionarioForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.ClientSize = new System.Drawing.Size(777, 450);
            this.Controls.Add(this.txtSearch);
            this.Controls.Add(this.dataGridViewfFuncionario);
            this.Controls.Add(this.bunifuButton3);
            this.Controls.Add(this.btneEdite);
            this.Controls.Add(this.btnInserir);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.tbUsername);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.tbNIF);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.tbNome);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FuncionarioForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "FuncionarioForm";
            this.Load += new System.EventHandler(this.FuncionarioForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewfFuncionario)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox tbNome;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox tbNIF;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox tbUsername;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInserir;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btneEdite;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private System.Windows.Forms.ToolStripButton fillBy12ToolStripButton;
        private System.Windows.Forms.DataGridView dataGridViewfFuncionario;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
    }
}