// <auto-generated />
namespace iCantina.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddEstadoReserva : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEstadoReserva));
        
        string IMigrationMetadata.Id
        {
            get { return "202406191400348_AddEstadoReserva"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
